version: "3.8"

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db:/app/db # Mapeia a pasta db para o diretório /app/db dentro do contêiner
    depends_on:
      - db # Garante que o banco esteja pronto antes de iniciar o backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/biblioteca # Definir URL de conexão do banco

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d/ # Certifique-se de que init.sql está em ./backend/db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
